# SPDX-License-Identifier: GPL-2.0-only

chv3-video-objs := \
	chv3-core.o \
	chv3-fb.o \
	dprx-aux.o \
	dprx-dp.o \
	dprx-dpcd.o \
	dprx-dprx.o \
	dprx-edid.o \
	dprx-i2c.o \
	dprx-mt.o \
	dprx-sbmsg.o

obj-$(CONFIG_VIDEO_CHAMELEONV3) += chv3-video.o
